In [1]:
import numpy as np

data = [
  [1, 2, 3],
  [4, None, 6],
  [7, 8, 9]
]

np_array = np.array(data)
np_array = np_array.astype(float)
np_array.dtype
np_array

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [2]:
np_array[1, 1] == np.nan

False

In [3]:
np.isnan(np_array[1, 1])

True

In [7]:
data = [
  [1, 2, 3],
  [4, -9999.0, 6],
  [7, 8, 9]
]

no_data_value = -9999.0
np_array = np.array(data, dtype=np.float32)
np_array = np.where(np_array == no_data_value, np.nan, np_array)
np_array

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [16]:
data = [
  [1, 2, 3],
  [4, None, 6],
  [7, 8, 9]
]

no_data_value = None
np_array = np.array(data, dtype=np.float32)
np_array[np.isnan(np_array)] = -9999.0
np_array

array([[ 1.000e+00,  2.000e+00,  3.000e+00],
       [ 4.000e+00, -9.999e+03,  6.000e+00],
       [ 7.000e+00,  8.000e+00,  9.000e+00]], dtype=float32)

In [13]:
np.isnan(np_array)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])